// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqkcntwkxvjwbmuhtjsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxa2NudHdreHZqd2JtdWh0anNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTg1NjgsImV4cCI6MjA2OTk3NDU2OH0.MDVtkttxzk_gb9oH2A7_A9hy6SzpenHsWnJfdSG5XjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});